# Introduction

In this notebook we'll learn how to use NumPy to work with numerical data.

<img src="https://i.imgur.com/dZ1XE9o.png" width=400>


# Import Statements


In [106]:
import numpy as np
from random import randint
import matplotlib.pyplot as plt
from scipy import misc  # contains an image of a racoon!
from PIL import Image  # for reading image files


# Understanding NumPy's ndarray

NumPy's most amazing feature is the **powerful** ndarray.

<img src="https://i.imgur.com/1IUqnxX.png" width=200>


In [160]:
def make_array(dim: int, nums: int, col: int = 1):
    if dim <= 0:
        raise ValueError("you are A Fucking IDIOT!")
    elif dim == col:
        return [randint(1,nums) for i in range(nums)]
    else:
        return list(eval("make_array(dim-1 ,nums, col)," * nums))


def test(dim: int, numbs: int, col: int = 1) -> None:
    array = make_array(dim, numbs, col)
    if type(array) == list:
        array = np.array(array)
        print(f"The Array:-\n{array}")
        print(f"The Number Of Dimension is :- {array.ndim}")
        print(f"The Shape Of Array is :- {array.shape}")


test(3, 5)

The Array:-
[[[4 3 4 1 5]
  [1 5 2 5 5]
  [3 4 1 2 2]
  [4 5 5 3 4]
  [3 1 3 2 3]]

 [[2 2 5 4 2]
  [4 4 4 3 5]
  [3 1 2 1 3]
  [2 2 2 3 5]
  [4 3 1 4 2]]

 [[1 4 4 2 1]
  [1 1 1 2 5]
  [4 3 4 1 3]
  [2 1 5 2 1]
  [2 5 5 4 3]]

 [[2 3 2 3 2]
  [4 4 1 5 5]
  [3 1 1 2 2]
  [2 4 3 2 4]
  [4 5 5 1 2]]

 [[4 2 4 2 2]
  [3 4 4 5 2]
  [3 4 5 1 3]
  [1 1 2 3 3]
  [5 5 2 3 3]]]
The Number Of Dimension is :- 3
The Shape Of Array is :- (5, 5, 5)


#### 1-Dimensional Arrays (Vectors)


In [161]:
test(5, 1)

The Array:-
[[[[[1]]]]]
The Number Of Dimension is :- 5
The Shape Of Array is :- (1, 1, 1, 1, 1)


#### 2-Dimensional Arrays (Matrices)


In [162]:
test(5, 2)


The Array:-
[[[[[1 2]
    [1 2]]

   [[2 1]
    [2 1]]]


  [[[1 1]
    [1 2]]

   [[1 2]
    [1 2]]]]



 [[[[2 1]
    [2 1]]

   [[2 2]
    [2 2]]]


  [[[1 1]
    [1 1]]

   [[2 1]
    [2 2]]]]]
The Number Of Dimension is :- 5
The Shape Of Array is :- (2, 2, 2, 2, 2)


#### N-Dimensional Arrays (Tensors)

**Challenge**:

-   How many dimensions does the array below have?
-   What is its shape (i.e., how many elements are along each axis)?
-   Try to access the value `18` in the last line of code.
-   Try to retrieve a 1 dimensional vector with the values `[97, 0, 27, 18]`
-   Try to retrieve a (3,2) matrix with the values `[[ 0,  4], [ 7,  5], [ 5, 97]]`

_Hint_: You can use the `:` operator just as with Python Lists.


In [101]:
mystery_array = np.array(
    [
        [[0, 1, 2, 3], [4, 5, 6, 7]],
        [[7, 86, 6, 98], [5, 1, 0, 4]],
        [[5, 36, 32, 48], [97, 0, 27, 18]],
    ]
)
mystery_array.shape

(3, 2, 4)

# NumPy Mini-Challenges


#### **Challenge 1**: Use [`.arange()`](https://numpy.org/devdocs/reference/generated/numpy.arange.html)to createa a vector `a` with values ranging from 10 to 29. You should get this:

`print(a)`

`[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]`


#### **Challenge 2**: Use Python slicing techniques on `a` to:

-   Create an array containing only the last 3 values of `a`
-   Create a subset with only the 4th, 5th, and 6th values
-   Create a subset of `a` containing all the values except for the first 12 (i.e., `[22, 23, 24, 25, 26, 27, 28, 29]`)
-   Create a subset that only contains the even numbers (i.e, every second number)


#### **Challenge 3**:Reverse the order of the values in `a`, so that the first element comes last:

`[29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10]`

If you need a hint, you can check out this part of the [NumPy beginner's guide](https://numpy.org/devdocs/user/absolute_beginners.html#how-to-reverse-an-array)


#### **Challenge 4**: Print out all the indices of the non-zero elements in this array: [6,0,9,0,0,5,0]


#### **Challenge 5**: Use NumPy to generate a 3x3x3 array with random numbers

Hint: Use the [`.random()` function](https://numpy.org/doc/stable/reference/random/index.html?highlight=random#module-numpy.random)


#### **Challenge 6**: Use [`.linspace()`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) to create a vector `x` of size 9 with values spaced out evenly between 0 to 100 (both included).


#### **Challenge 7**: Use [`.linspace()`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) to create another vector `y` of size 9 with values between -3 to 3 (both included). Then plot `x` and `y` on a line chart using Matplotlib.


#### **Challenge 8**: Use NumPy to generate an array called `noise` with shape 128x128x3 that has random values. Then use Matplotlib's [`.imshow()`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.imshow.html) to display the array as an image.


# Linear Algebra with Vectors


In [ ]:
v1 = np.array([4, 5, 2, 7])
v2 = np.array([2, 1, 3, 3])


In [ ]:
# Python Lists vs ndarrays
list1 = [4, 5, 2, 7]
list2 = [2, 1, 3, 3]


# Broadcasting and Scalars


# Matrix Multiplication with @ and .matmul()

<img src=https://i.imgur.com/LCdhmi8.png width=350>


In [ ]:
a1 = np.array([[1, 3], [0, 1], [6, 2], [9, 7]])

b1 = np.array([[4, 1, 3], [5, 8, 5]])

print(f"{a1.shape}: a has {a1.shape[0]} rows and {a1.shape[1]} columns.")
print(f"{b1.shape}: b has {b1.shape[0]} rows and {b1.shape[1]} columns.")
print("Dimensions of result: (4x2)*(2x3)=(4x3)")

**Challenge**: Let's multiply `a1` with `b1`. Looking at the wikipedia example above, work out the values for c12 and c33 on paper. Then use the [`.matmul()`](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) function or the `@` operator to check your work.


# Manipulating Images as ndarrays


**Challenge**: What is the data type of `img`? Also, what is the shape of `img` and how many dimensions does it have? What is the resolution of the image?


**Challenge**: Convert the image to black and white. The values in our `img` range from 0 to 255.

-   Divide all the values by 255 to convert them to sRGB, where all the values are between 0 and 1.
-   Next, multiply the sRGB array by the `grey_vals` to convert the image to grey scale.
-   Finally use Matplotlib's [`.imshow()`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.imshow.html) together with the colormap parameter set to gray `cmap=gray` to look at the results.


In [ ]:
grey_vals = np.array([0.2126, 0.7152, 0.0722])


**Challenge**: Can you manipulate the images by doing some operations on the underlying ndarrays? See if you can change the values in the ndarray so that:

1. You flip the grayscale image upside down

<img src=https://i.imgur.com/r36CigD.png>

2. Rotate the colour image

<img src=https://i.imgur.com/IiNylco.png>

3. Invert (i.e., solarize) the colour image. To do this you need to converting all the pixels to their "opposite" value, so black (0) becomes white (255).

<img src=https://i.imgur.com/cfFbuex.png>


#### Challenge Solutions


# Use your Own Image!


In [ ]:
file_name = "yummy_macarons.jpg"

#### Use PIL to open
